[package]
name = "lyzah"
version = "0.1.0"
authors = ["Frans Paasonen <franspaasonen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.30.0"
winit = "0.22.1"
crossbeam = "0.7.3"
